export const productMock = {
  id: "123456",
  name: "Giày thể thao nam thời trang năng động - Mẫu mới nhất 2025",
  slug: "giay-the-thao-nam-thoi-trang-nang-dong",
  brand: "XYZ",
  origin: "Việt Nam",
  material: "Vải + cao su",
  price: 999000,
  discountPrice: 499000,
  discountPercent: 50,
  stock: 245,
  sold: 1203,
  likedCount: 284,
  shop: {
    id: "shop001",
    name: "Shop Giày Chính Hãng",
    isVerified: true,
    rating: 4.9,
    followers: 10500,
    responseRate: 95,
    responseTime: "Trong vài giờ",
    joinDate: "2020-05-12",
    productsCount: 150,
    chatPerformance: "Rất tốt",
    address: "TP. Hồ Chí Minh",
  },
  shipping: {
    from: "TP. Hồ Chí Minh",
    fee: 0,
    freeShipping: true,
    estimatedDelivery: "3-5 ngày",
    shippingMethods: ["Nhanh", "Tiết kiệm", "Hỏa tốc"],
  },
  warranty: {
    type: "Bằng hóa đơn mua hàng",
    duration: "6 tháng",
    policy: "Đổi trả trong 7 ngày nếu lỗi từ nhà sản xuất",
  },
  labels: ["Yêu thích", "Hoàn xu X%", "Freeship Xtra", "Giảm giá đặc biệt"],
  flashSale: {
    isActive: true,
    salePrice: 459000,
    originalPrice: 999000,
    discountPercent: 54,
    endTime: "2025-07-10T23:59:59Z",
    quantity: 300,
    sold: 200,
  },
  images: [
    "/images/client/product/Product-1.webp",
    "/images/client/product/Product-2.webp",
    "/images/client/product/Product-3.webp",
    "/images/client/product/Product-1.webp",
    "/images/client/product/Product-2.webp",
    "/images/client/product/Product-3.webp",
    "/images/client/product/Product-1.webp",
    "/images/client/product/Product-2.webp",
    "/images/client/product/Product-3.webp",
    "/images/client/product/Product-1.webp",
    "/images/client/product/Product-2.webp",
    "/images/client/product/Product-3.webp",
    "/images/client/product/Product-1.webp",
    "/images/client/product/Product-2.webp",
    "/images/client/product/Product-3.webp",
  ],
  video: "https://www.youtube.com/watch?v=-l3JvyMHfEQ&list=RD-l3JvyMHfEQ&start_radio=1&pp=oAcB",
  specifications: [
    { name: "Chất liệu", value: "Vải + cao su" },
    { name: "Thương hiệu", value: "XYZ" },
    { name: "Xuất xứ", value: "Việt Nam" },
    { name: "Mẫu mã", value: "Sneaker cổ thấp" },
    { name: "Giới tính", value: "Nam" },
    { name: "Phong cách", value: "Thể thao, năng động" },
  ],
  variations: [
    {
      name: "Màu sắc",
      options: ["Đen", "Trắng", "Xám"],
    },
    {
      name: "Kích thước",
      options: ["38", "39", "40", "41", "42", "43"],
    },
  ],
  rating: 4.8,
  totalReviews: 287,
  reviews: [
    {
      user: "Nguyễn Văn A",
      rating: 5,
      comment: "Giày đẹp, đi rất êm chân. Shop đóng gói cẩn thận.",
      images: ["/sample-review-1.jpg"],
      date: "2025-06-01",
      boughtVariation: "Đen, size 41",
    },
    {
      user: "Trần Thị B",
      rating: 4,
      comment: "Đẹp, đúng mẫu. Giao hàng nhanh.",
      images: [],
      date: "2025-06-20",
      boughtVariation: "Trắng, size 40",
    },
  ],
  suggestions: [
    {
      id: "s1",
      name: "Giày sneaker nam cổ thấp",
      image: "/sample-product.jpg",
      price: 299000,
    },
    {
      id: "s2",
      name: "Giày thể thao nhẹ chạy bộ",
      image: "/sample-product.jpg",
      price: 399000,
    },
    {
      id: "s3",
      name: "Giày sneaker thời trang nữ",
      image: "/sample-product.jpg",
      price: 359000,
    },
    {
      id: "s4",
      name: "Giày tập gym thể thao",
      image: "/sample-product.jpg",
      price: 289000,
    },
  ],
};
